server:
  port: 8080

spring:
  application:
    name: api-gateway

  management:
    endpoints:
      web:
        exposure:
          include: health,info,gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/products/**