server:
  port: 8081

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # telling user-service my eureka server is running here
      register-with-eureka: true #Register this application with Eureka
      fetch-registry: true # this means this application is allowed to fetch info about other registerd services.
